<a href="https://colab.research.google.com/github/euamura/PNAD-analise-de-alfabetizados/blob/main/projeto_nba.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Projeto NBA

## Preparado ambiente

In [ ]:
# Montando o Google Drive
from google.colab import drive
drive.mount('/content/drive')

%cd /content/drive/MyDrive/pasta

import os
print(os.getcwd())

!ls

## ETL

In [ ]:
! pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.10/dist-packages (1.6.17)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.10/dist-packages (from kaggle) (1.17.0)
Requirement already satisfied: certifi>=2023.7.22 in /usr/local/lib/python3.10/dist-packages (from kaggle) (2024.12.14)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.32.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from kaggle) (4.67.1)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.10/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.2.3)
Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from kaggle) (6.2.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.10/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle) (3.10)

### importar bibliotecas

In [ ]:
import os
import sqlite3
import pandas as pd
import csv
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import numpy as np

### importar e conectar banco de dados

In [ ]:
# importar banco de dados do kaggle
import kagglehub

# Download latest version
path = kagglehub.dataset_download("wyattowalsh/basketball")

print("Path to dataset files:", path)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.5), please consider upgrading to the latest version (0.3.6).
Downloading from https://www.kaggle.com/api/v1/datasets/download/wyattowalsh/basketball?dataset_version_number=231...

100%|██████████| 697M/697M [00:07<00:00, 95.0MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/wyattowalsh/basketball/versions/231

In [ ]:
# caminho banco de dados
db_path = os.path.join(path, "nba.sqlite")
print(db_path)

/root/.cache/kagglehub/datasets/wyattowalsh/basketball/versions/231/nba.sqlite

In [ ]:
# conectar ao banco de dados
conn_origem = sqlite3.connect(db_path)
cursor_origem = conn_origem.cursor()

In [ ]:
# exibir tabelas do banco de dados kaggle
cursor_origem.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor_origem.fetchall()
print(tables)

[('game',), ('game_summary',), ('other_stats',), ('officials',), ('inactive_players',), ('game_info',), ('line_score',), ('play_by_play',), ('player',), ('team',), ('common_player_info',), ('team_details',), ('team_history',), ('draft_combine_stats',), ('draft_history',), ('team_info_common',)]

In [ ]:
# criar novo banco de dados
conn_destino = sqlite3.connect('nba_novo.db')
cursor_destino = conn_destino.cursor()

In [ ]:
# exibir tabelas no banco de dados nba_novo
cursor_destino.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor_destino.fetchall()
print(tables)

[('players',), ('teams',), ('games',), ('general_table',)]

## Consulta e Cruzamentos em SQL:

In [ ]:
# criar função de cruzamento de dados
def cruzamento_dados(query, new_table):
    df_resultado = pd.read_sql_query(query, conn_origem)
    df_resultado.to_sql(new_table, conn_destino, if_exists="replace", index=False)
    print(f"Tabela '{new_table}' criada no banco de destino com dados cruzados.")

In [ ]:
# visualizar estrutura das tabelas bd origem

## game
cursor_origem.execute("PRAGMA table_info('game')")
print("tabela game:", cursor_origem.fetchall())

## game_summary
cursor_origem.execute("PRAGMA table_info('game_summary')")
print("tabela game_summary:", cursor_origem.fetchall())

## other_stats
cursor_origem.execute("PRAGMA table_info('other_stats')")
print("tabela other_stats:", cursor_origem.fetchall())

## oficials
cursor_origem.execute("PRAGMA table_info('officials')")
print("tabela officials:", cursor_origem.fetchall())

## inactive_players
cursor_origem.execute("PRAGMA table_info('inactive_players')")
print("tabela inactive_players:", cursor_origem.fetchall())

## game_info
cursor_origem.execute("PRAGMA table_info('game_info')")
print("tabela game_info:", cursor_origem.fetchall())

## line_score
cursor_origem.execute("PRAGMA table_info('line_score')")
print("tabela line_score:", cursor_origem.fetchall())

## play_by_play
cursor_origem.execute("PRAGMA table_info('play_by_play')")
print("tabela play_by_play:", cursor_origem.fetchall())

## player
cursor_origem.execute("PRAGMA table_info('player')")
print("tabela player:", cursor_origem.fetchall())

## team
cursor_origem.execute("PRAGMA table_info('team')")
print("tabela team:", cursor_origem.fetchall())

## common_player_info
cursor_origem.execute("PRAGMA table_info('common_player_info')")
print("tabela common_player_info:", cursor_origem.fetchall())

## team_details
cursor_origem.execute("PRAGMA table_info('team_details')")
print("tabela team_details:", cursor_origem.fetchall())

## team_history
cursor_origem.execute("PRAGMA table_info('team_history')")
print("tabela team_history:", cursor_origem.fetchall())

## draft_combine_stats
cursor_origem.execute("PRAGMA table_info('draft_combine_stats')")
print("tabela draft_combine_stats:", cursor_origem.fetchall())

## draft_history
cursor_origem.execute("PRAGMA table_info('draft_history')")
print("tabela draft_history:", cursor_origem.fetchall())

## team_info_common
cursor_origem.execute("PRAGMA table_info('team_info_common')")
print("tabela team_info_common:", cursor_origem.fetchall())

tabela game: [(0, 'season_id', 'TEXT', 0, None, 0), (1, 'team_id_home', 'TEXT', 0, None, 0), (2, 'team_abbreviation_home', 'TEXT', 0, None, 0), (3, 'team_name_home', 'TEXT', 0, None, 0), (4, 'game_id', 'TEXT', 0, None, 0), (5, 'game_date', 'TIMESTAMP', 0, None, 0), (6, 'matchup_home', 'TEXT', 0, None, 0), (7, 'wl_home', 'TEXT', 0, None, 0), (8, 'min', 'INTEGER', 0, None, 0), (9, 'fgm_home', 'REAL', 0, None, 0), (10, 'fga_home', 'REAL', 0, None, 0), (11, 'fg_pct_home', 'REAL', 0, None, 0), (12, 'fg3m_home', 'REAL', 0, None, 0), (13, 'fg3a_home', 'REAL', 0, None, 0), (14, 'fg3_pct_home', 'REAL', 0, None, 0), (15, 'ftm_home', 'REAL', 0, None, 0), (16, 'fta_home', 'REAL', 0, None, 0), (17, 'ft_pct_home', 'REAL', 0, None, 0), (18, 'oreb_home', 'REAL', 0, None, 0), (19, 'dreb_home', 'REAL', 0, None, 0), (20, 'reb_home', 'REAL', 0, None, 0), (21, 'ast_home', 'REAL', 0, None, 0), (22, 'stl_home', 'REAL', 0, None, 0), (23, 'blk_home', 'REAL', 0, None, 0), (24, 'tov_home', 'REAL', 0, None, 0), (25, 'pf_home', 'REAL', 0, None, 0), (26, 'pts_home', 'REAL', 0, None, 0), (27, 'plus_minus_home', 'INTEGER', 0, None, 0), (28, 'video_available_home', 'INTEGER', 0, None, 0), (29, 'team_id_away', 'TEXT', 0, None, 0), (30, 'team_abbreviation_away', 'TEXT', 0, None, 0), (31, 'team_name_away', 'TEXT', 0, None, 0), (32, 'matchup_away', 'TEXT', 0, None, 0), (33, 'wl_away', 'TEXT', 0, None, 0), (34, 'fgm_away', 'REAL', 0, None, 0), (35, 'fga_away', 'REAL', 0, None, 0), (36, 'fg_pct_away', 'REAL', 0, None, 0), (37, 'fg3m_away', 'REAL', 0, None, 0), (38, 'fg3a_away', 'REAL', 0, None, 0), (39, 'fg3_pct_away', 'REAL', 0, None, 0), (40, 'ftm_away', 'REAL', 0, None, 0), (41, 'fta_away', 'REAL', 0, None, 0), (42, 'ft_pct_away', 'REAL', 0, None, 0), (43, 'oreb_away', 'REAL', 0, None, 0), (44, 'dreb_away', 'REAL', 0, None, 0), (45, 'reb_away', 'REAL', 0, None, 0), (46, 'ast_away', 'REAL', 0, None, 0), (47, 'stl_away', 'REAL', 0, None, 0), (48, 'blk_away', 'REAL', 0, None, 0), (49, 'tov_away', 'REAL', 0, None, 0), (50, 'pf_away', 'REAL', 0, None, 0), (51, 'pts_away', 'REAL', 0, None, 0), (52, 'plus_minus_away', 'INTEGER', 0, None, 0), (53, 'video_available_away', 'INTEGER', 0, None, 0), (54, 'season_type', 'TEXT', 0, None, 0)]
tabela game_summary: [(0, 'game_date_est', 'TIMESTAMP', 0, None, 0), (1, 'game_sequence', 'INTEGER', 0, None, 0), (2, 'game_id', 'TEXT', 0, None, 0), (3, 'game_status_id', 'INTEGER', 0, None, 0), (4, 'game_status_text', 'TEXT', 0, None, 0), (5, 'gamecode', 'TEXT', 0, None, 0), (6, 'home_team_id', 'TEXT', 0, None, 0), (7, 'visitor_team_id', 'TEXT', 0, None, 0), (8, 'season', 'TEXT', 0, None, 0), (9, 'live_period', 'INTEGER', 0, None, 0), (10, 'live_pc_time', 'TEXT', 0, None, 0), (11, 'natl_tv_broadcaster_abbreviation', 'TEXT', 0, None, 0), (12, 'live_period_time_bcast', 'TEXT', 0, None, 0), (13, 'wh_status', 'INTEGER', 0, None, 0)]
tabela other_stats: [(0, 'game_id', 'TEXT', 0, None, 0), (1, 'league_id', 'TEXT', 0, None, 0), (2, 'team_id_home', 'TEXT', 0, None, 0), (3, 'team_abbreviation_home', 'TEXT', 0, None, 0), (4, 'team_city_home', 'TEXT', 0, None, 0), (5, 'pts_paint_home', 'INTEGER', 0, None, 0), (6, 'pts_2nd_chance_home', 'INTEGER', 0, None, 0), (7, 'pts_fb_home', 'INTEGER', 0, None, 0), (8, 'largest_lead_home', 'INTEGER', 0, None, 0), (9, 'lead_changes', 'INTEGER', 0, None, 0), (10, 'times_tied', 'INTEGER', 0, None, 0), (11, 'team_turnovers_home', 'INTEGER', 0, None, 0), (12, 'total_turnovers_home', 'INTEGER', 0, None, 0), (13, 'team_rebounds_home', 'INTEGER', 0, None, 0), (14, 'pts_off_to_home', 'INTEGER', 0, None, 0), (15, 'team_id_away', 'TEXT', 0, None, 0), (16, 'team_abbreviation_away', 'TEXT', 0, None, 0), (17, 'team_city_away', 'TEXT', 0, None, 0), (18, 'pts_paint_away', 'INTEGER', 0, None, 0), (19, 'pts_2nd_chance_away', 'INTEGER', 0, None, 0), (20, 'pts_fb_away', 'INTEGER', 0, None, 0), (21, 'largest_lead_away', 'INTEGER', 0, None, 0), (22, 'team_turnovers_away', 'INTEGER', 0, None, 0), (23, 'total_turnovers_away', 'INTEGER', 0, None, 0), (24, 'team_rebounds_away', 'INTEGER', 0, None, 0), (25, 'pts_off_to_away', 'INTEGER', 0, None, 0)]
tabela officials: [(0, 'game_id', 'TEXT', 0, None, 0), (1, 'official_id', 'TEXT', 0, None, 0), (2, 'first_name', 'TEXT', 0, None, 0), (3, 'last_name', 'TEXT', 0, None, 0), (4, 'jersey_num', 'TEXT', 0, None, 0)]
tabela inactive_players: [(0, 'game_id', 'TEXT', 0, None, 0), (1, 'player_id', 'TEXT', 0, None, 0), (2, 'first_name', 'TEXT', 0, None, 0), (3, 'last_name', 'TEXT', 0, None, 0), (4, 'jersey_num', 'TEXT', 0, None, 0), (5, 'team_id', 'TEXT', 0, None, 0), (6, 'team_city', 'TEXT', 0, None, 0), (7, 'team_name', 'TEXT', 0, None, 0), (8, 'team_abbreviation', 'TEXT', 0, None, 0)]
tabela game_info: [(0, 'game_id', 'TEXT', 0, None, 0), (1, 'game_date', 'TIMESTAMP', 0, None, 0), (2, 'attendance', 'INTEGER', 0, None, 0), (3, 'game_time', 'TEXT', 0, None, 0)]
tabela line_score: [(0, 'game_date_est', 'TIMESTAMP', 0, None, 0), (1, 'game_sequence', 'INTEGER', 0, None, 0), (2, 'game_id', 'TEXT', 0, None, 0), (3, 'team_id_home', 'TEXT', 0, None, 0), (4, 'team_abbreviation_home', 'TEXT', 0, None, 0), (5, 'team_city_name_home', 'TEXT', 0, None, 0), (6, 'team_nickname_home', 'TEXT', 0, None, 0), (7, 'team_wins_losses_home', 'TEXT', 0, None, 0), (8, 'pts_qtr1_home', 'TEXT', 0, None, 0), (9, 'pts_qtr2_home', 'TEXT', 0, None, 0), (10, 'pts_qtr3_home', 'TEXT', 0, None, 0), (11, 'pts_qtr4_home', 'TEXT', 0, None, 0), (12, 'pts_ot1_home', 'INTEGER', 0, None, 0), (13, 'pts_ot2_home', 'INTEGER', 0, None, 0), (14, 'pts_ot3_home', 'INTEGER', 0, None, 0), (15, 'pts_ot4_home', 'INTEGER', 0, None, 0), (16, 'pts_ot5_home', 'INTEGER', 0, None, 0), (17, 'pts_ot6_home', 'INTEGER', 0, None, 0), (18, 'pts_ot7_home', 'INTEGER', 0, None, 0), (19, 'pts_ot8_home', 'INTEGER', 0, None, 0), (20, 'pts_ot9_home', 'INTEGER', 0, None, 0), (21, 'pts_ot10_home', 'INTEGER', 0, None, 0), (22, 'pts_home', 'REAL', 0, None, 0), (23, 'team_id_away', 'TEXT', 0, None, 0), (24, 'team_abbreviation_away', 'TEXT', 0, None, 0), (25, 'team_city_name_away', 'TEXT', 0, None, 0), (26, 'team_nickname_away', 'TEXT', 0, None, 0), (27, 'team_wins_losses_away', 'TEXT', 0, None, 0), (28, 'pts_qtr1_away', 'INTEGER', 0, None, 0), (29, 'pts_qtr2_away', 'TEXT', 0, None, 0), (30, 'pts_qtr3_away', 'TEXT', 0, None, 0), (31, 'pts_qtr4_away', 'INTEGER', 0, None, 0), (32, 'pts_ot1_away', 'INTEGER', 0, None, 0), (33, 'pts_ot2_away', 'INTEGER', 0, None, 0), (34, 'pts_ot3_away', 'INTEGER', 0, None, 0), (35, 'pts_ot4_away', 'INTEGER', 0, None, 0), (36, 'pts_ot5_away', 'INTEGER', 0, None, 0), (37, 'pts_ot6_away', 'INTEGER', 0, None, 0), (38, 'pts_ot7_away', 'INTEGER', 0, None, 0), (39, 'pts_ot8_away', 'INTEGER', 0, None, 0), (40, 'pts_ot9_away', 'INTEGER', 0, None, 0), (41, 'pts_ot10_away', 'INTEGER', 0, None, 0), (42, 'pts_away', 'REAL', 0, None, 0)]
tabela play_by_play: [(0, 'game_id', 'TEXT', 0, None, 0), (1, 'eventnum', 'INTEGER', 0, None, 0), (2, 'eventmsgtype', 'INTEGER', 0, None, 0), (3, 'eventmsgactiontype', 'INTEGER', 0, None, 0), (4, 'period', 'INTEGER', 0, None, 0), (5, 'wctimestring', 'TEXT', 0, None, 0), (6, 'pctimestring', 'TEXT', 0, None, 0), (7, 'homedescription', 'TEXT', 0, None, 0), (8, 'neutraldescription', 'TEXT', 0, None, 0), (9, 'visitordescription', 'TEXT', 0, None, 0), (10, 'score', 'TEXT', 0, None, 0), (11, 'scoremargin', 'TEXT', 0, None, 0), (12, 'person1type', 'REAL', 0, None, 0), (13, 'player1_id', 'TEXT', 0, None, 0), (14, 'player1_name', 'TEXT', 0, None, 0), (15, 'player1_team_id', 'TEXT', 0, None, 0), (16, 'player1_team_city', 'TEXT', 0, None, 0), (17, 'player1_team_nickname', 'TEXT', 0, None, 0), (18, 'player1_team_abbreviation', 'TEXT', 0, None, 0), (19, 'person2type', 'REAL', 0, None, 0), (20, 'player2_id', 'TEXT', 0, None, 0), (21, 'player2_name', 'TEXT', 0, None, 0), (22, 'player2_team_id', 'TEXT', 0, None, 0), (23, 'player2_team_city', 'TEXT', 0, None, 0), (24, 'player2_team_nickname', 'TEXT', 0, None, 0), (25, 'player2_team_abbreviation', 'TEXT', 0, None, 0), (26, 'person3type', 'REAL', 0, None, 0), (27, 'player3_id', 'TEXT', 0, None, 0), (28, 'player3_name', 'TEXT', 0, None, 0), (29, 'player3_team_id', 'TEXT', 0, None, 0), (30, 'player3_team_city', 'TEXT', 0, None, 0), (31, 'player3_team_nickname', 'TEXT', 0, None, 0), (32, 'player3_team_abbreviation', 'TEXT', 0, None, 0), (33, 'video_available_flag', 'TEXT', 0, None, 0)]
tabela player: [(0, 'id', 'TEXT', 0, None, 0), (1, 'full_name', 'TEXT', 0, None, 0), (2, 'first_name', 'TEXT', 0, None, 0), (3, 'last_name', 'TEXT', 0, None, 0), (4, 'is_active', 'INTEGER', 0, None, 0)]
tabela team: [(0, 'id', 'TEXT', 0, None, 0), (1, 'full_name', 'TEXT', 0, None, 0), (2, 'abbreviation', 'TEXT', 0, None, 0), (3, 'nickname', 'TEXT', 0, None, 0), (4, 'city', 'TEXT', 0, None, 0), (5, 'state', 'TEXT', 0, None, 0), (6, 'year_founded', 'REAL', 0, None, 0)]
tabela common_player_info: [(0, 'person_id', 'TEXT', 0, None, 0), (1, 'first_name', 'TEXT', 0, None, 0), (2, 'last_name', 'TEXT', 0, None, 0), (3, 'display_first_last', 'TEXT', 0, None, 0), (4, 'display_last_comma_first', 'TEXT', 0, None, 0), (5, 'display_fi_last', 'TEXT', 0, None, 0), (6, 'player_slug', 'TEXT', 0, None, 0), (7, 'birthdate', 'TIMESTAMP', 0, None, 0), (8, 'school', 'TEXT', 0, None, 0), (9, 'country', 'TEXT', 0, None, 0), (10, 'last_affiliation', 'TEXT', 0, None, 0), (11, 'height', 'TEXT', 0, None, 0), (12, 'weight', 'TEXT', 0, None, 0), (13, 'season_exp', 'REAL', 0, None, 0), (14, 'jersey', 'TEXT', 0, None, 0), (15, 'position', 'TEXT', 0, None, 0), (16, 'rosterstatus', 'TEXT', 0, None, 0), (17, 'games_played_current_season_flag', 'TEXT', 0, None, 0), (18, 'team_id', 'INTEGER', 0, None, 0), (19, 'team_name', 'TEXT', 0, None, 0), (20, 'team_abbreviation', 'TEXT', 0, None, 0), (21, 'team_code', 'TEXT', 0, None, 0), (22, 'team_city', 'TEXT', 0, None, 0), (23, 'playercode', 'TEXT', 0, None, 0), (24, 'from_year', 'REAL', 0, None, 0), (25, 'to_year', 'REAL', 0, None, 0), (26, 'dleague_flag', 'TEXT', 0, None, 0), (27, 'nba_flag', 'TEXT', 0, None, 0), (28, 'games_played_flag', 'TEXT', 0, None, 0), (29, 'draft_year', 'TEXT', 0, None, 0), (30, 'draft_round', 'TEXT', 0, None, 0), (31, 'draft_number', 'TEXT', 0, None, 0), (32, 'greatest_75_flag', 'TEXT', 0, None, 0)]
tabela team_details: [(0, 'team_id', 'TEXT', 0, None, 0), (1, 'abbreviation', 'TEXT', 0, None, 0), (2, 'nickname', 'TEXT', 0, None, 0), (3, 'yearfounded', 'REAL', 0, None, 0), (4, 'city', 'TEXT', 0, None, 0), (5, 'arena', 'TEXT', 0, None, 0), (6, 'arenacapacity', 'REAL', 0, None, 0), (7, 'owner', 'TEXT', 0, None, 0), (8, 'generalmanager', 'TEXT', 0, None, 0), (9, 'headcoach', 'TEXT', 0, None, 0), (10, 'dleagueaffiliation', 'TEXT', 0, None, 0), (11, 'facebook', 'TEXT', 0, None, 0), (12, 'instagram', 'TEXT', 0, None, 0), (13, 'twitter', 'TEXT', 0, None, 0)]
tabela team_history: [(0, 'team_id', 'TEXT', 0, None, 0), (1, 'city', 'TEXT', 0, None, 0), (2, 'nickname', 'TEXT', 0, None, 0), (3, 'year_founded', 'INTEGER', 0, None, 0), (4, 'year_active_till', 'INTEGER', 0, None, 0)]
tabela draft_combine_stats: [(0, 'season', 'TEXT', 0, None, 0), (1, 'player_id', 'TEXT', 0, None, 0), (2, 'first_name', 'TEXT', 0, None, 0), (3, 'last_name', 'TEXT', 0, None, 0), (4, 'player_name', 'TEXT', 0, None, 0), (5, 'position', 'TEXT', 0, None, 0), (6, 'height_wo_shoes', 'REAL', 0, None, 0), (7, 'height_wo_shoes_ft_in', 'TEXT', 0, None, 0), (8, 'height_w_shoes', 'REAL', 0, None, 0), (9, 'height_w_shoes_ft_in', 'TEXT', 0, None, 0), (10, 'weight', 'TEXT', 0, None, 0), (11, 'wingspan', 'REAL', 0, None, 0), (12, 'wingspan_ft_in', 'TEXT', 0, None, 0), (13, 'standing_reach', 'REAL', 0, None, 0), (14, 'standing_reach_ft_in', 'TEXT', 0, None, 0), (15, 'body_fat_pct', 'TEXT', 0, None, 0), (16, 'hand_length', 'TEXT', 0, None, 0), (17, 'hand_width', 'TEXT', 0, None, 0), (18, 'standing_vertical_leap', 'REAL', 0, None, 0), (19, 'max_vertical_leap', 'REAL', 0, None, 0), (20, 'lane_agility_time', 'REAL', 0, None, 0), (21, 'modified_lane_agility_time', 'REAL', 0, None, 0), (22, 'three_quarter_sprint', 'REAL', 0, None, 0), (23, 'bench_press', 'REAL', 0, None, 0), (24, 'spot_fifteen_corner_left', 'TEXT', 0, None, 0), (25, 'spot_fifteen_break_left', 'TEXT', 0, None, 0), (26, 'spot_fifteen_top_key', 'TEXT', 0, None, 0), (27, 'spot_fifteen_break_right', 'TEXT', 0, None, 0), (28, 'spot_fifteen_corner_right', 'TEXT', 0, None, 0), (29, 'spot_college_corner_left', 'TEXT', 0, None, 0), (30, 'spot_college_break_left', 'TEXT', 0, None, 0), (31, 'spot_college_top_key', 'TEXT', 0, None, 0), (32, 'spot_college_break_right', 'TEXT', 0, None, 0), (33, 'spot_college_corner_right', 'TEXT', 0, None, 0), (34, 'spot_nba_corner_left', 'TEXT', 0, None, 0), (35, 'spot_nba_break_left', 'TEXT', 0, None, 0), (36, 'spot_nba_top_key', 'TEXT', 0, None, 0), (37, 'spot_nba_break_right', 'TEXT', 0, None, 0), (38, 'spot_nba_corner_right', 'TEXT', 0, None, 0), (39, 'off_drib_fifteen_break_left', 'TEXT', 0, None, 0), (40, 'off_drib_fifteen_top_key', 'TEXT', 0, None, 0), (41, 'off_drib_fifteen_break_right', 'TEXT', 0, None, 0), (42, 'off_drib_college_break_left', 'TEXT', 0, None, 0), (43, 'off_drib_college_top_key', 'TEXT', 0, None, 0), (44, 'off_drib_college_break_right', 'TEXT', 0, None, 0), (45, 'on_move_fifteen', 'TEXT', 0, None, 0), (46, 'on_move_college', 'TEXT', 0, None, 0)]
tabela draft_history: [(0, 'person_id', 'TEXT', 0, None, 0), (1, 'player_name', 'TEXT', 0, None, 0), (2, 'season', 'TEXT', 0, None, 0), (3, 'round_number', 'INTEGER', 0, None, 0), (4, 'round_pick', 'INTEGER', 0, None, 0), (5, 'overall_pick', 'INTEGER', 0, None, 0), (6, 'draft_type', 'TEXT', 0, None, 0), (7, 'team_id', 'TEXT', 0, None, 0), (8, 'team_city', 'TEXT', 0, None, 0), (9, 'team_name', 'TEXT', 0, None, 0), (10, 'team_abbreviation', 'TEXT', 0, None, 0), (11, 'organization', 'TEXT', 0, None, 0), (12, 'organization_type', 'TEXT', 0, None, 0), (13, 'player_profile_flag', 'TEXT', 0, None, 0)]
tabela team_info_common: [(0, 'team_id', 'TEXT', 0, None, 0), (1, 'season_year', 'TEXT', 0, None, 0), (2, 'team_city', 'TEXT', 0, None, 0), (3, 'team_name', 'TEXT', 0, None, 0), (4, 'team_abbreviation', 'TEXT', 0, None, 0), (5, 'team_conference', 'TEXT', 0, None, 0), (6, 'team_division', 'TEXT', 0, None, 0), (7, 'team_code', 'TEXT', 0, None, 0), (8, 'team_slug', 'TEXT', 0, None, 0), (9, 'w', 'INTEGER', 0, None, 0), (10, 'l', 'INTEGER', 0, None, 0), (11, 'pct', 'REAL', 0, None, 0), (12, 'conf_rank', 'INTEGER', 0, None, 0), (13, 'div_rank', 'INTEGER', 0, None, 0), (14, 'min_year', 'INTEGER', 0, None, 0), (15, 'max_year', 'INTEGER', 0, None, 0), (16, 'league_id', 'TEXT', 0, None, 0), (17, 'season_id', 'TEXT', 0, None, 0), (18, 'pts_rank', 'INTEGER', 0, None, 0), (19, 'pts_pg', 'REAL', 0, None, 0), (20, 'reb_rank', 'INTEGER', 0, None, 0), (21, 'reb_pg', 'REAL', 0, None, 0), (22, 'ast_rank', 'INTEGER', 0, None, 0), (23, 'ast_pg', 'REAL', 0, None, 0), (24, 'opp_pts_rank', 'INTEGER', 0, None, 0), (25, 'opp_pts_pg', 'REAL', 0, None, 0)]

In [ ]:
# criar tabela e cruzar dados para banco de destino

## players
query1 = '''
  SELECT
    p.id AS player_id,
    p.full_name AS player_name,
    cp.team_id,
    cp.position,
    cp.height,
    cp.birthdate
  FROM player p
  JOIN common_player_info cp ON p.id = cp.person_id
'''

cruzamento_dados(query1, 'players')

## teams
query2 = '''
  SELECT
    t.id AS team_id,
    t.full_name AS team_name,
    t.city,
    td.arena
  FROM team t
  JOIN team_details td ON t.id = td.team_id
'''

cruzamento_dados(query2, 'teams')

## games
query3 = '''
  SELECT
    g.game_id,
    g.team_id_home AS team_id,
    g.game_date,
    g.pts_home AS score,
    g.wl_home AS win_lose,
    g.ast_home AS assists,
    g.reb_home AS rebounds
  FROM game g
'''

cruzamento_dados(query3, 'games')

Tabela 'players' criada no banco de destino com dados cruzados.
Tabela 'teams' criada no banco de destino com dados cruzados.
Tabela 'games' criada no banco de destino com dados cruzados.

In [ ]:
# exibir dados tabela no bd de destino
cursor_destino.execute("PRAGMA table_info('players')")
print("tabela players:", cursor_destino.fetchall())

cursor_destino.execute("PRAGMA table_info('teams')")
print("tabela teams:", cursor_destino.fetchall())

cursor_destino.execute("PRAGMA table_info('games')")
print("tabela games:", cursor_destino.fetchall())

tabela players: [(0, 'player_id', 'TEXT', 0, None, 0), (1, 'player_name', 'TEXT', 0, None, 0), (2, 'team_id', 'INTEGER', 0, None, 0), (3, 'position', 'TEXT', 0, None, 0), (4, 'height', 'TEXT', 0, None, 0), (5, 'birthdate', 'TEXT', 0, None, 0)]
tabela teams: [(0, 'team_id', 'TEXT', 0, None, 0), (1, 'team_name', 'TEXT', 0, None, 0), (2, 'city', 'TEXT', 0, None, 0), (3, 'arena', 'TEXT', 0, None, 0)]
tabela games: [(0, 'game_id', 'TEXT', 0, None, 0), (1, 'team_id', 'TEXT', 0, None, 0), (2, 'game_date', 'TEXT', 0, None, 0), (3, 'score', 'REAL', 0, None, 0), (4, 'win_lose', 'TEXT', 0, None, 0), (5, 'assists', 'REAL', 0, None, 0), (6, 'rebounds', 'REAL', 0, None, 0)]

In [ ]:
# criar tabela com união de dados do bd de destino

cursor_destino.execute( '''
CREATE TABLE IF NOT EXISTS general_table AS
  SELECT
    g.*,
    t.team_name,
    t.city,
    t.arena,
    p.player_id,
    P.player_name,
    P.position,
    P.height,
    P.birthdate
  FROM games g
  JOIN teams t ON g.team_id = t.team_id
  JOIN players p ON g.team_id = p.team_id
  WHERE game_date >= DATE('now', '-10 years');

''')
conn_destino.commit()

In [ ]:
cursor_destino.execute("PRAGMA table_info('general_table')")
print("tabela general_table:", cursor_destino.fetchall())

tabela general_table: [(0, 'game_id', 'TEXT', 0, None, 0), (1, 'team_id', 'TEXT', 0, None, 0), (2, 'game_date', 'TEXT', 0, None, 0), (3, 'score', 'REAL', 0, None, 0), (4, 'win_lose', 'TEXT', 0, None, 0), (5, 'assists', 'REAL', 0, None, 0), (6, 'rebounds', 'REAL', 0, None, 0), (7, 'team_name', 'TEXT', 0, None, 0), (8, 'city', 'TEXT', 0, None, 0), (9, 'arena', 'TEXT', 0, None, 0), (10, 'player_id', 'TEXT', 0, None, 0), (11, 'player_name', 'TEXT', 0, None, 0), (12, 'position', 'TEXT', 0, None, 0), (13, 'height', 'TEXT', 0, None, 0), (14, 'birthdate', 'TEXT', 0, None, 0)]

## Extração para DataFrame Pandas

In [ ]:
extracao_dados = '''
SELECT * FROM general_table
'''
df = pd.read_sql_query(extracao_dados, conn_destino)

In [ ]:
# fechar conexão com banco de dados
conn_origem.close()
conn_destino.close()

In [ ]:
df

,game_id,team_id,game_date,score,win_lose,assists,rebounds,team_name,city,arena,player_id,player_name,position,height,birthdate
0,0021400584,1610612745,2015-01-15 00:00:00,112.0,W,25.0,41.0,Houston Rockets,Houston,Toyota Center,101144,Von Wafer,Guard,6-5,1985-07-21 00:00:00
1,0021400584,1610612745,2015-01-15 00:00:00,112.0,W,25.0,41.0,Houston Rockets,Houston,Toyota Center,1038,Juaquin Hawkins,Forward,6-7,1973-07-02 00:00:00
2,0021400584,1610612745,2015-01-15 00:00:00,112.0,W,25.0,41.0,Houston Rockets,Houston,Toyota Center,137,Vernon Maxwell,Guard,6-4,1965-09-12 00:00:00
3,0021400584,1610612745,2015-01-15 00:00:00,112.0,W,25.0,41.0,Houston Rockets,Houston,Toyota Center,1509,Kelvin Cato,Center,6-11,1974-08-26 00:00:00
4,0021400584,1610612745,2015-01-15 00:00:00,112.0,W,25.0,41.0,Houston Rockets,Houston,Toyota Center,1622,Rodney McCray,Forward,6-8,1961-08-29 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
987220,0042200405,1610612743,2023-06-12 00:00:00,94.0,W,21.0,57.0,Denver Nuggets,Denver,Ball Arena,78566,Pete Williams,Forward,6-7,1965-03-10 00:00:00
987221,0042200405,1610612743,2023-06-12 00:00:00,94.0,W,21.0,57.0,Denver Nuggets,Denver,Ball Arena,78602,Willie Wise,Forward,6-6,1947-03-03 00:00:00
987222,0042200405,1610612743,2023-06-12 00:00:00,94.0,W,21.0,57.0,Denver Nuggets,Denver,Ball Arena,78656,Blair Rasmussen,Forward,6-4,1962-11-13 00:00:00
987223,0042200405,1610612743,2023-06-12 00:00:00,94.0,W,21.0,57.0,Denver Nuggets,Denver,Ball Arena,87,Dikembe Mutombo,Center,7-2,1966-06-25 00:00:00
987224,0042200405,1610612743,2023-06-12 00:00:00,94.0,W,21.0,57.0,Denver Nuggets,Denver,Ball Arena,948,Marcus Camby,Center-Forward,6-11,1974-03-22 00:00:00

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 987225 entries, 0 to 987224
Data columns (total 15 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   game_id      987225 non-null  object
 1   team_id      987225 non-null  object
 2   game_date    987225 non-null  object
 3   score        987225 non-null  float64
 4   win_lose     987225 non-null  object
 5   assists      987225 non-null  float64
 6   rebounds     987225 non-null  float64
 7   team_name    987225 non-null  object
 8   city         987225 non-null  object
 9   arena        987225 non-null  object
 10  player_id    987225 non-null  object
 11  player_name  987225 non-null  object
 12  position     987225 non-null  object
 13  height       987225 non-null  object
 14  birthdate    987225 non-null  object
dtypes: float64(3), object(12)
memory usage: 113.0+ MB

In [ ]:
df.describe()

               score        assists       rebounds
count  987225.000000  987225.000000  987225.000000
mean      109.718972      24.292095      44.700791
std        12.956665       5.224284       6.639720
min        64.000000       9.000000      22.000000
25%       101.000000      21.000000      40.000000
50%       110.000000      24.000000      45.000000
75%       118.000000      28.000000      49.000000
max       175.000000      47.000000      70.000000

## Limpeza e Tratamento

In [ ]:
# conferir nulos
df.isnull().sum()

game_id        0
team_id        0
game_date      0
score          0
win_lose       0
assists        0
rebounds       0
team_name      0
city           0
arena          0
player_id      0
player_name    0
position       0
height         0
birthdate      0
dtype: int64

In [ ]:
df.head(150)

,game_id,team_id,game_date,score,win_lose,assists,rebounds,team_name,city,arena,player_id,player_name,position,height,birthdate
0,0021400584,1610612745,2015-01-15 00:00:00,112.0,W,25.0,41.0,Houston Rockets,Houston,Toyota Center,101144,Von Wafer,Guard,6-5,1985-07-21 00:00:00
1,0021400584,1610612745,2015-01-15 00:00:00,112.0,W,25.0,41.0,Houston Rockets,Houston,Toyota Center,1038,Juaquin Hawkins,Forward,6-7,1973-07-02 00:00:00
2,0021400584,1610612745,2015-01-15 00:00:00,112.0,W,25.0,41.0,Houston Rockets,Houston,Toyota Center,137,Vernon Maxwell,Guard,6-4,1965-09-12 00:00:00
3,0021400584,1610612745,2015-01-15 00:00:00,112.0,W,25.0,41.0,Houston Rockets,Houston,Toyota Center,1509,Kelvin Cato,Center,6-11,1974-08-26 00:00:00
4,0021400584,1610612745,2015-01-15 00:00:00,112.0,W,25.0,41.0,Houston Rockets,Houston,Toyota Center,1622,Rodney McCray,Forward,6-8,1961-08-29 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,0021400586,1610612747,2015-01-15 00:00:00,102.0,L,26.0,35.0,Los Angeles Lakers,Los Angeles,Crypto.com Arena,76332,Demetrius Calip,Guard,6-1,1969-11-18 00:00:00
146,0021400586,1610612747,2015-01-15 00:00:00,102.0,L,26.0,35.0,Los Angeles Lakers,Los Angeles,Crypto.com Arena,76344,Don Carlson,Guard,6-0,1921-03-22 00:00:00
147,0021400586,1610612747,2015-01-15 00:00:00,102.0,L,26.0,35.0,Los Angeles Lakers,Los Angeles,Crypto.com Arena,76345,Bob Carney,Center,6-3,1932-08-03 00:00:00
148,0021400586,1610612747,2015-01-15 00:00:00,102.0,L,26.0,35.0,Los Angeles Lakers,Los Angeles,Crypto.com Arena,76361,Ron Carter,Guard,6-5,1956-08-31 00:00:00
149,0021400586,1610612747,2015-01-15 00:00:00,102.0,L,26.0,35.0,Los Angeles Lakers,Los Angeles,Crypto.com Arena,76444,Michael Cooper,Guard,6-7,1956-04-15 00:00:00

In [ ]:
#consultar duplciados
duplicados_game_id = df['game_id'].duplicated().sum()
duplicados_player_id = df['player_id'].duplicated().sum()
duplicados = df.duplicated(subset = ['game_id', 'player_id']).sum()

print("Número de duplicados na coluna 'game_id':", duplicados_game_id)
print("Número de duplicados na coluna 'player_id':", duplicados_player_id)
print("Número de duplicados na coluna 'game_id' e 'player_id':", duplicados)

Número de duplicados na coluna 'game_id': 976936
Número de duplicados na coluna 'player_id': 984643
Número de duplicados na coluna 'game_id' e 'player_id': 0

Nota importante: Decisão para os duplicados: neste caso é preciso considerar que cada jogador tenha jogado cada jogo apenas uma vez. Portanto levando em conta que o resultado do subset da váriavel duplicados é 0. Não é prudente remover duplicados a partir de uma chave.

In [ ]:
# transformação de dados
df['game_date'] = pd.to_datetime(df['game_date'])
df['birthdate'] = pd.to_datetime(df['birthdate'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 987225 entries, 0 to 987224
Data columns (total 15 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   game_id      987225 non-null  object
 1   team_id      987225 non-null  object
 2   game_date    987225 non-null  datetime64[ns]
 3   score        987225 non-null  float64
 4   win_lose     987225 non-null  object
 5   assists      987225 non-null  float64
 6   rebounds     987225 non-null  float64
 7   team_name    987225 non-null  object
 8   city         987225 non-null  object
 9   arena        987225 non-null  object
 10  player_id    987225 non-null  object
 11  player_name  987225 non-null  object
 12  position     987225 non-null  object
 13  height       987225 non-null  object
 14  birthdate    987225 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(3), object(10)
memory usage: 113.0+ MB

In [ ]:
# criar copia df
df_copia = df.copy()

# agrupar copia df
df_teams = df_copia.groupby(['team_id','team_name'])
df_teams.head()

,game_id,team_id,game_date,score,win_lose,assists,rebounds,team_name,city,arena,player_id,player_name,position,height,birthdate
0,0021400584,1610612745,2015-01-15,112.0,W,25.0,41.0,Houston Rockets,Houston,Toyota Center,101144,Von Wafer,Guard,6-5,1985-07-21
1,0021400584,1610612745,2015-01-15,112.0,W,25.0,41.0,Houston Rockets,Houston,Toyota Center,1038,Juaquin Hawkins,Forward,6-7,1973-07-02
2,0021400584,1610612745,2015-01-15,112.0,W,25.0,41.0,Houston Rockets,Houston,Toyota Center,137,Vernon Maxwell,Guard,6-4,1965-09-12
3,0021400584,1610612745,2015-01-15,112.0,W,25.0,41.0,Houston Rockets,Houston,Toyota Center,1509,Kelvin Cato,Center,6-11,1974-08-26
4,0021400584,1610612745,2015-01-15,112.0,W,25.0,41.0,Houston Rockets,Houston,Toyota Center,1622,Rodney McCray,Forward,6-8,1961-08-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3367,0021400631,1610612750,2015-01-21,75.0,L,22.0,43.0,Minnesota Timberwolves,Minnesota,Target Center,101152,Bracey Wright,Guard,6-3,1984-07-01
3368,0021400631,1610612750,2015-01-21,75.0,L,22.0,43.0,Minnesota Timberwolves,Minnesota,Target Center,1627752,Taurean Prince,Forward,6-6,1994-03-22
3369,0021400631,1610612750,2015-01-21,75.0,L,22.0,43.0,Minnesota Timberwolves,Minnesota,Target Center,1627875,Marcus Georges-Hunt,Guard,6-5,1994-03-28
3370,0021400631,1610612750,2015-01-21,75.0,L,22.0,43.0,Minnesota Timberwolves,Minnesota,Target Center,1629123,Jared Terrell,Guard,6-3,1995-02-10
3371,0021400631,1610612750,2015-01-21,75.0,L,22.0,43.0,Minnesota Timberwolves,Minnesota,Target Center,1629162,Jordan McLaughlin,Guard,6-0,1996-04-09

In [ ]:
# criar copia df
df_copia = df.copy()

# agrupar copia df
df_player = df_copia.groupby(['player_id', 'player_name'])
df_player.head()

,game_id,team_id,game_date,score,win_lose,assists,rebounds,team_name,city,arena,player_id,player_name,position,height,birthdate
0,0021400584,1610612745,2015-01-15,112.0,W,25.0,41.0,Houston Rockets,Houston,Toyota Center,101144,Von Wafer,Guard,6-5,1985-07-21
1,0021400584,1610612745,2015-01-15,112.0,W,25.0,41.0,Houston Rockets,Houston,Toyota Center,1038,Juaquin Hawkins,Forward,6-7,1973-07-02
2,0021400584,1610612745,2015-01-15,112.0,W,25.0,41.0,Houston Rockets,Houston,Toyota Center,137,Vernon Maxwell,Guard,6-4,1965-09-12
3,0021400584,1610612745,2015-01-15,112.0,W,25.0,41.0,Houston Rockets,Houston,Toyota Center,1509,Kelvin Cato,Center,6-11,1974-08-26
4,0021400584,1610612745,2015-01-15,112.0,W,25.0,41.0,Houston Rockets,Houston,Toyota Center,1622,Rodney McCray,Forward,6-8,1961-08-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26113,0021400886,1610612751,2015-03-02,110.0,W,20.0,38.0,Brooklyn Nets,Brooklyn,Barclays Center,78464,Duane Washington,Guard,6-4,1964-08-31
26114,0021400886,1610612751,2015-03-02,110.0,W,20.0,38.0,Brooklyn Nets,Brooklyn,Barclays Center,78465,Dwayne Washington,Guard,6-2,1964-01-06
26115,0021400886,1610612751,2015-03-02,110.0,W,20.0,38.0,Brooklyn Nets,Brooklyn,Barclays Center,78471,Wilson Washington,Forward,6-9,1955-08-03
26116,0021400886,1610612751,2015-03-02,110.0,W,20.0,38.0,Brooklyn Nets,Brooklyn,Barclays Center,78575,John Williamson,Guard,6-2,1951-11-10
26117,0021400886,1610612751,2015-03-02,110.0,W,20.0,38.0,Brooklyn Nets,Brooklyn,Barclays Center,78611,Leon Wood,Guard,6-3,1962-03-25

## Análise Estatística e Visualizações

### Manipulação dos Dados

####  1. Calcular a pontuação por jogador

In [ ]:
# calcular pontos por jogador
pontos_por_jogador = df_player.apply(lambda x: x['score'].sum())
pontos_por_jogador

<ipython-input-71-d1a43954abac>:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  pontos_por_jogador = df_player.apply(lambda x: x['score'].sum())

player_id  player_name
1000       Shandon Anderson    38246.0
100263     Bill Laimbeer       37836.0
1006       Herb Williams       39871.0
1007       Luther Wright       41226.0
101        Scott Skiles        38108.0
                                ...
986        Marcus Mann         49286.0
987        Jason Sasser        40681.0
988        Randy Livingston    42212.0
997        Chris Robinson      40681.0
998        Mark Pope           44577.0
Length: 2582, dtype: float64

In [ ]:
# transformar pontos_por_jogador em df
df_pontos_por_jogador = pd.DataFrame(pontos_por_jogador, columns=['pontos_por_jogador'])
df_pontos_por_jogador

                            pontos_por_jogador
player_id player_name
1000      Shandon Anderson             38246.0
100263    Bill Laimbeer                37836.0
1006      Herb Williams                39871.0
1007      Luther Wright                41226.0
101       Scott Skiles                 38108.0
...                                        ...
986       Marcus Mann                  49286.0
987       Jason Sasser                 40681.0
988       Randy Livingston             42212.0
997       Chris Robinson               40681.0
998       Mark Pope                    44577.0

[2582 rows x 1 columns]

In [ ]:

df_pontos_por_jogador.describe()

       pontos_por_jogador
count          2582.00000
mean          41950.93416
std            2910.70036
min           37836.00000
25%           39871.00000
50%           42021.00000
75%           43288.00000
max           49286.00000

In [ ]:
df_pontos_por_jogador.max()

pontos_por_jogador    49286.0
dtype: float64

In [ ]:
df_pontos_por_jogador.min()

pontos_por_jogador    37836.0
dtype: float64

In [ ]:
q1 = df_pontos_por_jogador.quantile(0.25)
q2 = df_pontos_por_jogador.quantile(0.5)
q3 = df_pontos_por_jogador.quantile(0.75)
q4 = df_pontos_por_jogador.quantile(1)

print("Q1:", q1)
print("Q2:", q2)
print("Q3:", q3)
print("Q4:", q4)

Q1: pontos_por_jogador    39871.0
Name: 0.25, dtype: float64
Q2: pontos_por_jogador    42021.0
Name: 0.5, dtype: float64
Q3: pontos_por_jogador    43288.0
Name: 0.75, dtype: float64
Q4: pontos_por_jogador    49286.0
Name: 1.0, dtype: float64

#### 2. Agrupar os dados por time e calcular a média de pontuação, rebotes e assistências

In [ ]:
# média de pontuação, rebotes e assistências agrupados por time
medias = df_teams[['score', 'rebounds', 'assists']].agg('mean')
medias

                                        score   rebounds    assists
team_id    team_name
1610612737 Atlanta Hawks           110.581579  44.302632  25.468421
1610612738 Boston Celtics          110.417874  45.082126  25.086957
1610612739 Cleveland Cavaliers     108.378446  43.756892  23.937343
1610612740 New Orleans Pelicans    111.367403  45.116022  25.770718
1610612741 Chicago Bulls           106.201087  45.138587  23.967391
1610612742 Dallas Mavericks        108.128686  43.058981  22.635389
1610612743 Denver Nuggets          112.436364  45.314286  26.823377
1610612744 Golden State Warriors   114.618605  45.306977  29.148837
1610612745 Houston Rockets         112.369620  44.359494  22.984810
1610612746 Los Angeles Clippers    111.268542  44.677749  24.092072
1610612747 Los Angeles Lakers      108.335038  45.445013  23.759591
1610612748 Miami Heat              107.500000  43.397500  23.297500
1610612749 Milwaukee Bucks         111.442500  46.045000  24.847500
1610612750 Minnesota Timberwolves  109.495775  43.616901  24.428169
1610612751 Brooklyn Nets           108.883784  44.589189  23.908108
1610612752 New York Knicks         105.944598  45.246537  21.864266
1610612753 Orlando Magic           105.270718  44.439227  23.511050
1610612754 Indiana Pacers          109.235616  43.493151  24.493151
1610612755 Philadelphia 76ers      109.431169  44.571429  25.374026
1610612756 Phoenix Suns            109.927083  44.406250  23.953125
1610612757 Portland Trail Blazers  111.952000  45.234667  22.168000
1610612758 Sacramento Kings        110.260623  42.745042  24.070822
1610612760 Oklahoma City Thunder   110.706349  46.187831  22.661376
1610612761 Toronto Raptors         110.175879  44.140704  22.567839
1610612762 Utah Jazz               108.775726  45.781003  22.134565
1610612763 Memphis Grizzlies       107.055263  45.250000  23.913158
1610612765 Detroit Pistons         106.280899  44.626404  23.308989

In [ ]:
# criar df com médias de pontos, rebotes e assistencias por time
df_medias_por_time = pd.DataFrame(medias)
df_medias_por_time

                                        score   rebounds    assists
team_id    team_name
1610612737 Atlanta Hawks           110.581579  44.302632  25.468421
1610612738 Boston Celtics          110.417874  45.082126  25.086957
1610612739 Cleveland Cavaliers     108.378446  43.756892  23.937343
1610612740 New Orleans Pelicans    111.367403  45.116022  25.770718
1610612741 Chicago Bulls           106.201087  45.138587  23.967391
1610612742 Dallas Mavericks        108.128686  43.058981  22.635389
1610612743 Denver Nuggets          112.436364  45.314286  26.823377
1610612744 Golden State Warriors   114.618605  45.306977  29.148837
1610612745 Houston Rockets         112.369620  44.359494  22.984810
1610612746 Los Angeles Clippers    111.268542  44.677749  24.092072
1610612747 Los Angeles Lakers      108.335038  45.445013  23.759591
1610612748 Miami Heat              107.500000  43.397500  23.297500
1610612749 Milwaukee Bucks         111.442500  46.045000  24.847500
1610612750 Minnesota Timberwolves  109.495775  43.616901  24.428169
1610612751 Brooklyn Nets           108.883784  44.589189  23.908108
1610612752 New York Knicks         105.944598  45.246537  21.864266
1610612753 Orlando Magic           105.270718  44.439227  23.511050
1610612754 Indiana Pacers          109.235616  43.493151  24.493151
1610612755 Philadelphia 76ers      109.431169  44.571429  25.374026
1610612756 Phoenix Suns            109.927083  44.406250  23.953125
1610612757 Portland Trail Blazers  111.952000  45.234667  22.168000
1610612758 Sacramento Kings        110.260623  42.745042  24.070822
1610612760 Oklahoma City Thunder   110.706349  46.187831  22.661376
1610612761 Toronto Raptors         110.175879  44.140704  22.567839
1610612762 Utah Jazz               108.775726  45.781003  22.134565
1610612763 Memphis Grizzlies       107.055263  45.250000  23.913158
1610612765 Detroit Pistons         106.280899  44.626404  23.308989

In [ ]:
# renomear colunas de df_medias_por_time
df_medias_por_time = df_medias_por_time.rename(columns={'score': 'score_mean', 'rebounds': 'rebounds_mean', 'assists': 'assists_mean'})
df_medias_por_time

                                   score_mean  rebounds_mean  assists_mean
team_id    team_name
1610612737 Atlanta Hawks           110.581579      44.302632     25.468421
1610612738 Boston Celtics          110.417874      45.082126     25.086957
1610612739 Cleveland Cavaliers     108.378446      43.756892     23.937343
1610612740 New Orleans Pelicans    111.367403      45.116022     25.770718
1610612741 Chicago Bulls           106.201087      45.138587     23.967391
1610612742 Dallas Mavericks        108.128686      43.058981     22.635389
1610612743 Denver Nuggets          112.436364      45.314286     26.823377
1610612744 Golden State Warriors   114.618605      45.306977     29.148837
1610612745 Houston Rockets         112.369620      44.359494     22.984810
1610612746 Los Angeles Clippers    111.268542      44.677749     24.092072
1610612747 Los Angeles Lakers      108.335038      45.445013     23.759591
1610612748 Miami Heat              107.500000      43.397500     23.297500
1610612749 Milwaukee Bucks         111.442500      46.045000     24.847500
1610612750 Minnesota Timberwolves  109.495775      43.616901     24.428169
1610612751 Brooklyn Nets           108.883784      44.589189     23.908108
1610612752 New York Knicks         105.944598      45.246537     21.864266
1610612753 Orlando Magic           105.270718      44.439227     23.511050
1610612754 Indiana Pacers          109.235616      43.493151     24.493151
1610612755 Philadelphia 76ers      109.431169      44.571429     25.374026
1610612756 Phoenix Suns            109.927083      44.406250     23.953125
1610612757 Portland Trail Blazers  111.952000      45.234667     22.168000
1610612758 Sacramento Kings        110.260623      42.745042     24.070822
1610612760 Oklahoma City Thunder   110.706349      46.187831     22.661376
1610612761 Toronto Raptors         110.175879      44.140704     22.567839
1610612762 Utah Jazz               108.775726      45.781003     22.134565
1610612763 Memphis Grizzlies       107.055263      45.250000     23.913158
1610612765 Detroit Pistons         106.280899      44.626404     23.308989

In [ ]:
# média de pontuação
df_teams['score'].mean()

team_id     team_name
1610612737  Atlanta Hawks             110.581579
1610612738  Boston Celtics            110.417874
1610612739  Cleveland Cavaliers       108.378446
1610612740  New Orleans Pelicans      111.367403
1610612741  Chicago Bulls             106.201087
1610612742  Dallas Mavericks          108.128686
1610612743  Denver Nuggets            112.436364
1610612744  Golden State Warriors     114.618605
1610612745  Houston Rockets           112.369620
1610612746  Los Angeles Clippers      111.268542
1610612747  Los Angeles Lakers        108.335038
1610612748  Miami Heat                107.500000
1610612749  Milwaukee Bucks           111.442500
1610612750  Minnesota Timberwolves    109.495775
1610612751  Brooklyn Nets             108.883784
1610612752  New York Knicks           105.944598
1610612753  Orlando Magic             105.270718
1610612754  Indiana Pacers            109.235616
1610612755  Philadelphia 76ers        109.431169
1610612756  Phoenix Suns              109.927083
1610612757  Portland Trail Blazers    111.952000
1610612758  Sacramento Kings          110.260623
1610612760  Oklahoma City Thunder     110.706349
1610612761  Toronto Raptors           110.175879
1610612762  Utah Jazz                 108.775726
1610612763  Memphis Grizzlies         107.055263
1610612765  Detroit Pistons           106.280899
Name: score, dtype: float64

In [ ]:
# media de rebotes
df_teams['rebounds'].mean()

team_id     team_name
1610612737  Atlanta Hawks             44.302632
1610612738  Boston Celtics            45.082126
1610612739  Cleveland Cavaliers       43.756892
1610612740  New Orleans Pelicans      45.116022
1610612741  Chicago Bulls             45.138587
1610612742  Dallas Mavericks          43.058981
1610612743  Denver Nuggets            45.314286
1610612744  Golden State Warriors     45.306977
1610612745  Houston Rockets           44.359494
1610612746  Los Angeles Clippers      44.677749
1610612747  Los Angeles Lakers        45.445013
1610612748  Miami Heat                43.397500
1610612749  Milwaukee Bucks           46.045000
1610612750  Minnesota Timberwolves    43.616901
1610612751  Brooklyn Nets             44.589189
1610612752  New York Knicks           45.246537
1610612753  Orlando Magic             44.439227
1610612754  Indiana Pacers            43.493151
1610612755  Philadelphia 76ers        44.571429
1610612756  Phoenix Suns              44.406250
1610612757  Portland Trail Blazers    45.234667
1610612758  Sacramento Kings          42.745042
1610612760  Oklahoma City Thunder     46.187831
1610612761  Toronto Raptors           44.140704
1610612762  Utah Jazz                 45.781003
1610612763  Memphis Grizzlies         45.250000
1610612765  Detroit Pistons           44.626404
Name: rebounds, dtype: float64

In [ ]:
# média de assistencias
df_teams['assists'].mean()

team_id     team_name
1610612737  Atlanta Hawks             25.468421
1610612738  Boston Celtics            25.086957
1610612739  Cleveland Cavaliers       23.937343
1610612740  New Orleans Pelicans      25.770718
1610612741  Chicago Bulls             23.967391
1610612742  Dallas Mavericks          22.635389
1610612743  Denver Nuggets            26.823377
1610612744  Golden State Warriors     29.148837
1610612745  Houston Rockets           22.984810
1610612746  Los Angeles Clippers      24.092072
1610612747  Los Angeles Lakers        23.759591
1610612748  Miami Heat                23.297500
1610612749  Milwaukee Bucks           24.847500
1610612750  Minnesota Timberwolves    24.428169
1610612751  Brooklyn Nets             23.908108
1610612752  New York Knicks           21.864266
1610612753  Orlando Magic             23.511050
1610612754  Indiana Pacers            24.493151
1610612755  Philadelphia 76ers        25.374026
1610612756  Phoenix Suns              23.953125
1610612757  Portland Trail Blazers    22.168000
1610612758  Sacramento Kings          24.070822
1610612760  Oklahoma City Thunder     22.661376
1610612761  Toronto Raptors           22.567839
1610612762  Utah Jazz                 22.134565
1610612763  Memphis Grizzlies         23.913158
1610612765  Detroit Pistons           23.308989
Name: assists, dtype: float64

#### 3. Classificar jogadores com base na pontuação usando cut e criar categorias de performance

### Estatísticas Descritivas

Após a manipulação inicial dos dados, os alunos devem calcular as principais estatísticas descritivas para variáveis de interesse, como pontuação, rebotes e assistências

####  1. Média, Mediana, Desvio Padrão e Quartis

### Probabilidade e Amostragem

Aqui, os alunos devem calcular a probabilidade de eventos específicos ocorrerem, como a probabilidade de um time ganhar ou um jogador alcançar uma pontuação acima de um determinado valor.

#### 1. Probabilidade de um jogador marcar mais de 20 pontos

#### 2. Criar amostras de 30% dos dados para realizar análises estatísticas posteriores.

### Testes de Hipóteses

Agora, vocês devem realizar testes de hipóteses. Suponha que queremos testar se a média de pontos dos jogadores em casa é diferente da média de pontos dos jogadores em jogos fora de casa. Para isso, utilizaremos o Teste T.

### Visualizações dos Dados

#### 1. Boxplot da Pontuação por Categoria de Jogador

#### 2. Distribuição de Idade dos Jogadores com histograma

#### 3. Gráfico de Barras mostrando a Relação entre Pontuação e Rebotes por Time

## Conclusão da Análise